### ISSUE TITLE
Request for dataset

### ISSUE THREAD

**Issue by StarDewXXX** [zankner/CLoud#1]
Hi, your work is really creative! I want to reproduce your experiment but I don't have enough computing resources for generating datasets. Will you release it on Huggingface?

**Comment by zankner** [comment]
Thank you for the kind words! We have released the datasets on huggingface. [HF Space](https://huggingface.co/collections/ankner/critique-out-loud-reward-models-66d9e34cceaea3df9f78cef8)

Please refer to the datasets section of the README to download the datasets and structure the data properly .[(https://github.com/zankner/CLoud?tab=readme-ov-file#dataset)](https://github.com/zankner/CLoud?tab=readme-ov-file#dataset).

If you have any further questions please don't hesitate to ask.
